
import { pgTable, text, serial, integer, boolean, timestamp, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  email: text("email").notNull().unique(),
  password: text("password").notNull(),
  fullName: text("full_name").notNull(),
  role: text("role").default("student"), // "student" | "admin"
  createdAt: timestamp("created_at").defaultNow(),
});

export const interviews = pgTable("interviews", {
  id: serial("id").primaryKey(),
  userId: integer("user_id"),
  subjectId: integer("subject_id"), // optional link to subject for topic-based practice
  title: text("title").notNull(),
  description: text("description").notNull(),
  link: text("link"),
  status: text("status").default("in_progress"), // in_progress, completed
  overallScore: integer("overall_score"),
  summary: jsonb("summary"), // { strengths: [], weaknesses: [], revision_topics: [], project_improvements: [] }
  createdAt: timestamp("created_at").defaultNow(),
  completedAt: timestamp("completed_at"),
});

export const messages = pgTable("messages", {
  id: serial("id").primaryKey(),
  interviewId: integer("interview_id").notNull(),
  role: text("role").notNull(), // "interviewer" | "candidate"
  content: text("content").notNull(),
  feedback: jsonb("feedback"), // { rating: number, explanation: string, sample_answer: string, common_mistakes: string }
  createdAt: timestamp("created_at").defaultNow(),
});

export const appSettings = pgTable("app_settings", {
  id: serial("id").primaryKey(),
  key: text("key").notNull().unique(),
  value: text("value").notNull(),
});

export const subjects = pgTable("subjects", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  icon: text("icon"), // lucide icon name
  isPreset: boolean("is_preset").default(false), // preset vs user-created
  createdAt: timestamp("created_at").defaultNow(),
});

export const userSubjects = pgTable("user_subjects", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  subjectId: integer("subject_id").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const studyMaterials = pgTable("study_materials", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  subjectId: integer("subject_id").notNull(),
  fileName: text("file_name").notNull(),
  fileType: text("file_type").notNull(), // pdf, txt, md
  content: text("content"), // extracted text content for AI
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertUserSchema = createInsertSchema(users).omit({
  id: true,
  role: true,
  createdAt: true
});

export const insertSubjectSchema = createInsertSchema(subjects).omit({
  id: true,
  createdAt: true
});

export const insertStudyMaterialSchema = createInsertSchema(studyMaterials).omit({
  id: true,
  createdAt: true
});

export const loginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(6),
});

export const insertInterviewSchema = createInsertSchema(interviews).omit({ 
  id: true, 
  userId: true,
  status: true, 
  overallScore: true, 
  summary: true, 
  createdAt: true 
});

export const insertMessageSchema = createInsertSchema(messages).omit({ 
  id: true, 
  createdAt: true,
  feedback: true // Feedback is generated by server
});

export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type Interview = typeof interviews.$inferSelect;
export type InsertInterview = z.infer<typeof insertInterviewSchema>;
export type Message = typeof messages.$inferSelect;
export type InsertMessage = z.infer<typeof insertMessageSchema>;

export type FeedbackData = {
  rating: number; // 0-10
  explanation: string;
  sample_answer: string;
  common_mistakes: string;
};

export type SummaryData = {
  overall_score: number;
  strengths: string[];
  weaknesses: string[];
  revision_topics: string[];
  project_improvements: string[];
  response_count?: number;
};

export type Subject = typeof subjects.$inferSelect;
export type InsertSubject = z.infer<typeof insertSubjectSchema>;
export type UserSubject = typeof userSubjects.$inferSelect;
export type StudyMaterial = typeof studyMaterials.$inferSelect;
export type InsertStudyMaterial = z.infer<typeof insertStudyMaterialSchema>;
